Import upstream version 4.2

diff --git a/usr/bin/byobu b/usr/bin/byobu
--- a/usr/bin/byobu
+++ b/usr/bin/byobu
@@ -18,16 +18,17 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 PKG="byobu"
-VERSION=4.1
+VERSION=4.2
 [ -z "$BYOBU_PREFIX" ] && export BYOBU_PREFIX="/usr"
 export BYOBU_PREFIX
 [ -r "/etc/$PKG/socketdir" ] && . "/etc/$PKG/socketdir" || SOCKETDIR="/var/run/screen"
 RUN="$SOCKETDIR/S-$USER"
 DATA="$HOME/.$PKG"
 
+. "${BYOBU_PREFIX}/lib/${PKG}/.shutil"
 if [ ! -x "$BYOBU_PREFIX/bin/$PKG" ]; then
-	echo "ERROR: Cannot find $BYOBU_PREFIX/bin/$PKG" 2>&1
-	echo "ERROR: If you have installed it elsewhere, export BYOBU_PREFIX in your shell" 2>&1
+	error "Cannot find $BYOBU_PREFIX/bin/$PKG"
+	error "If you have installed it elsewhere, export BYOBU_PREFIX in your shell"
 	exit 1
 fi
 
@@ -36,7 +37,7 @@ if [ "$#" = "1" ]; then
 	case "$1" in
 		-v|--version)
 			echo "$PKG version $VERSION"
-			screen -v
+			exec screen -v
 			exit 0
 		;;
 	esac
@@ -51,7 +52,7 @@ fi
 byobu-janitor --force
 
 # Set the window title
-[ -z "$BYOBU_NO_TITLE" ] || printf "\033]0;${USER}@$(hostname) - ${PKG}\007"
+[ -z "$BYOBU_NO_TITLE" ] || printf "\033]0;${USER}@${HOSTNAME:-$(hostname)} - ${PKG}\007"
 
 # Allow override of default window list, with BYOBU_WINDOWS environment variable
 CUSTOM_WINDOW_SET=0
@@ -68,14 +69,17 @@ fi
 export BYOBU_WINDOWS
 
 # Launch shell, unless the user has default windows set to launch
-grep -qs "^[^#]" "$BYOBU_WINDOWS" && DEFAULT_WINDOW= || DEFAULT_WINDOW="shell"
+uncommented_lines < "$BYOBU_WINDOWS" && DEFAULT_WINDOW= || DEFAULT_WINDOW="shell"
 
 # Check if our terminfo supports 256 colors
-$(which tput >/dev/null) && [ $(tput colors 2>/dev/null || echo 0) -eq 256 ] && SCREEN_TERM="-T screen-256color"
+if command -v tput >/dev/null; then
+	if [ "$(tput colors 2>/dev/null || echo 0)" = "256" ]; then
+		SCREEN_TERM="-T screen-256color"
+	fi
+fi
 
 # Drop a symlink to the ssh socket in $HOME, since we can ensure that exists
 if [ -S "$SSH_AUTH_SOCK" ] && [ ! -h "$SSH_AUTH_SOCK" ]; then
-	rm -f "$DATA/.ssh-agent"
 	ln -sf "$SSH_AUTH_SOCK" "$DATA/.ssh-agent"
 fi
 
@@ -88,7 +92,7 @@ else
 fi
 NAME="-S $PKG"
 # Zero out $NAME if user has specified a -S
-for i in $@; do
+for i in "$@"; do
 	case $i in -*S|-ls|-list) NAME= ;; esac
 done
 # Now let's execute screen!
diff --git a/usr/bin/byobu-silent b/usr/bin/byobu-silent
--- a/usr/bin/byobu-silent
+++ b/usr/bin/byobu-silent
@@ -1,9 +1,9 @@
-#!/bin/sh -e
+#!/bin/sh
 #
-#    date - print the date in YYYY-MM-DD format
-#    Copyright (C) 2008 Canonical Ltd.
+#    byobu-silence - disable the hardstatus, all indicators, and the window list
+#    Copyright (C) 2011 Canonical Ltd.
 #
-#    Authors: Dustin Kirkland <kirkland@canonical.com>
+#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -17,18 +17,16 @@
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-case "$1" in
-	--detail)
-		date
-	;;
-	--short)
-		date +%Y-%m-%d
-	;;
-	*)
-		bd=$(date "+%m%d")
-		[ "$bd" = "0320" ] &&
-			msg="$(echo SGFwcHkgQmlydGhkYXkgU2NyZWVuIC0tIGh0dHA6Ly9iaXQubHkvc2NyZWVuLWJkYXkK | base64 -di)" &&
-			screen -X -S "byobu" at "*" echo "[$msg]"
-		printf "\005Y-\005m-\005d "
-	;;
-esac
+
+PKG="byobu"
+FLAG="$HOME/.$PKG/status.disable"
+
+# Clean up environment
+sed -i "/caption/d" "$HOME/.$PKG/keybindings" || true
+if [ "$1" = "--undo" ]; then
+	rm -f "$FLAG"
+else
+	touch "$FLAG"
+	echo "caption splitonly ''" >> "$HOME/.$PKG/keybindings"
+fi
+exec byobu-quiet "$@"
