Import upstream version 4.35

diff --git a/usr/bin/byobu-janitor b/usr/bin/byobu-janitor
--- a/usr/bin/byobu-janitor
+++ b/usr/bin/byobu-janitor
@@ -46,6 +46,12 @@ if [ -d "$BYOBU_CONFIG_DIR" ] && [ ! -w "$BYOBU_CONFIG_DIR" ]; then
 	exit 1
 fi
 
+# Affects: Upgrades from <= byobu 4.30
+# Clear out old style status configuration
+if ! grep -qs "^screen_upper_left=" "$BYOBU_CONFIG_DIR/status"; then
+	rm -f "$BYOBU_CONFIG_DIR/status" "$BYOBU_CONFIG_DIR/statusrc"
+fi
+
 # Affects: First runs with no configuration
 # Seed the configuration
 # Setup initial local user configuration
@@ -59,6 +65,10 @@ for f in status statusrc; do
 	if [ ! -r "$BYOBU_CONFIG_DIR/$f" ]; then
 		# Copy from skeleton, if possible
 		cp -f "$BYOBU_PREFIX/share/$PKG/status/$f" "$BYOBU_CONFIG_DIR/$f"
+		# Enable ec2_cost, if we're in ec2 and seeding a new setup
+		if metadata_available; then
+			$SED -i -e "s/#ec2_cost/ec2_cost/g" "$BYOBU_CONFIG_DIR/$f"
+		fi
 	fi
 done
 
@@ -123,7 +133,7 @@ fi
 # Affects: Upgrades from <= byobu 4.22
 killall -u $USER byobu-statusd >/dev/null 2>&1 || true
 
-# Clean up flag
-rm -f "$FLAG"
+# Clean up flag (new and old)
+rm -f "$FLAG" "/var/run/screen/S-$USER/$PKG.reload-required"
 
 # vi: syntax=sh ts=4 noexpandtab
