Import upstream version 4.0

diff --git a/usr/bin/byobu-quiet b/usr/bin/byobu-quiet
--- a/usr/bin/byobu-quiet
+++ b/usr/bin/byobu-quiet
@@ -1,10 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 #
-#    byobu-time-notifications: performance testing of byobu's status scripts
+#    byobu-quiet - disable the hardstatus and all indicators
+#    Copyright (C) 2011 Canonical Ltd.
 #
-#    Copyright (C) 2009 Canonical Ltd.
-#
-#    Authors: Dustin Kirkland <kirkland@canonical.com>
+#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -19,30 +18,17 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 
-PKG=byobu
-RUNS=10
-[ -z "$BYOBU_PREFIX" ] && BYOBU_PREFIX="/usr"
-export BYOBU_PREFIX
+PKG="byobu"
+FLAG="$HOME/.$PKG/status.disable"
 
-loop() {
-	for j in $(seq 1 $RUNS); do
-		usr/lib/$PKG/$1 >/dev/null 2>&1
-	done
-}
-
-TIMEFORMAT="%R"
-if [ -n "$1" ]; then
-	list="$1"
+# Clean up environment
+sed -i "/hardstatus/d" "$HOME/.$PKG/keybindings" || true
+if [ "$1" = "--undo" ]; then
+	rm -f "$FLAG"
 else
-	list=$(ls /usr/lib/$PKG/)
+	touch "$FLAG"
+	# BUG: Need to make this dynamic and following
+	status="$USER@$(hostname)"
+	echo "hardstatus lastline '$status'" >> "$HOME/.$PKG/keybindings"
 fi
-for i in $list; do
-	case "$i" in
-		notify_osd)
-			continue
-		;;
-	esac
-	freq=`grep "byobu-status $i$" /usr/share/$PKG/profiles/common | awk '{print $3}'`
-	echo -n "$i $freq "
-	time loop $i
-done
+screen -X at 0 source "$HOME/.$PKG/profile"
