Import upstream version 3.0

diff --git a/usr/bin/byobu b/usr/bin/byobu
--- a/usr/bin/byobu
+++ b/usr/bin/byobu
@@ -18,7 +18,15 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 PKG="byobu"
-VERSION=2.82
+VERSION=3.1
+[ -z "$BYOBU_PREFIX" ] && export BYOBU_PREFIX="/usr"
+export BYOBU_PREFIX
+
+if [ ! -x "$BYOBU_PREFIX/bin/$PKG" ]; then
+	echo "ERROR: Cannot find $BYOBU_PREFIX/bin/$PKG" 2>&1
+	echo "ERROR: If you have installed it elsewhere, export BYOBU_PREFIX in your shell" 2>&1
+	exit 1
+fi
 
 # Add a version argument for debugging purposes
 if [ "$#" = "1" ] && [ "$1" = "-v" ]; then
@@ -56,7 +64,7 @@ export BYOBU_WINDOWS
 grep -qs "^[^#]" "$BYOBU_WINDOWS" && DEFAULT_WINDOW= || DEFAULT_WINDOW="shell"
 
 # Check if our terminfo supports 256 colors
-[ -x /usr/bin/tput ] && [ $(/usr/bin/tput colors 2>/dev/null || echo 0) -eq 256 ] && SCREEN_TERM="-T screen-256color"
+$(which tput >/dev/null) && [ $(tput colors 2>/dev/null || echo 0) -eq 256 ] && SCREEN_TERM="-T screen-256color"
 
 # Create or update ssh-agent socket
 if [ -S "$SSH_AUTH_SOCK" ] && [ ! -h "$SSH_AUTH_SOCK" ] && [ -w "$RUN" ]; then
@@ -64,13 +72,18 @@ if [ -S "$SSH_AUTH_SOCK" ] && [ ! -h "$SSH_AUTH_SOCK" ] && [ -w "$RUN" ]; then
 	ln -sf "$SSH_AUTH_SOCK" "$RUN/$PKG.ssh-agent"
 fi
 
-PROFILE="-c /usr/share/$PKG/profiles/byoburc"
+PROFILE="-c $BYOBU_PREFIX/share/$PKG/profiles/byoburc"
+NAME="-S $PKG"
+# Zero out $NAME if user has specified a -S
+for i in $@; do
+	case $i in -S) NAME= ;; esac
+done
 # Now let's execute screen!
 if [ "$#" = "0" ]; then
 	out=$(screen -wipe 2>/dev/null) || true
 	if [ "$CUSTOM_WINDOW_SET" = "1" ]; then
 		# Start new custom window set session
-		exec screen $SCREEN_TERM -S $PKG $PROFILE
+		exec screen $SCREEN_TERM $NAME $PROFILE
 	else
 		case "$out" in
 			*\(*\)*)
@@ -79,11 +92,11 @@ if [ "$#" = "0" ]; then
 			;;
 			*)
 				# Start new default session
-				exec screen $SCREEN_TERM -S $PKG $PROFILE $DEFAULT_WINDOW
+				exec screen $SCREEN_TERM $NAME $PROFILE $DEFAULT_WINDOW
 			;;
 		esac
 	fi
 else
 	# Launch with command line args
-	exec screen $SCREEN_TERM -S $PKG $PROFILE "$@"
+	exec screen $SCREEN_TERM $NAME $PROFILE "$@"
 fi
